spring.application.name=solartrack-backend

# 🌟 Aiven का एकदम असली और सटीक कनेक्शन URL (सही पोर्ट 19609 के साथ)
spring.datasource.url=jdbc:mysql://mysql-a2f2dcf-ganeshpawar1316-6279.h.aivencloud.com:19609/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin

# पासवर्ड पूरी तरह सुरक्षित रहेगा, गिटहब इसे कभी ब्लॉक नहीं करेगा
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# रेंडर के लिए पोर्ट बाइंडिंग सेटिंग्स
server.port=8080